Личный проект: больше подробностей (часть 1)
htmlacademy-react/16780-six-cities-5 pull request #6
Opened 2020-10-15 11:59 UTC by aozubrilin

2020-10-15 12:05 UTC, phwb requested changes

2020-10-15 12:05 UTC, phwb commented on src/components/main/main.jsx
> +  const OffersInCity = offers.filter((it) => it.city === currentCity);
это же переменная, именуй правильно

2020-10-15 12:05 UTC, phwb commented on src/components/main/main.jsx
> +const currentCity = `Amsterdam`;
по сути это константа, но так как это все равно временное решение, то ок

2020-10-15 12:05 UTC, phwb commented on src/components/map/map.jsx
> +    const map = leaflet.map(`map`, {
нужно через ref делать, а не через айдишник

2020-10-15 15:14 UTC, phwb commented on src/components/main/main.jsx
> +  const OffersInCity = offers.filter((it) => it.city === currentCity);
а это почему не поправил?

2020-10-15 19:23 UTC, aozubrilin commented on src/components/main/main.jsx
> +  const OffersInCity = offers.filter((it) => it.city === currentCity);
Невнимательность... исправил, но не сохранил.

2020-10-16 02:18 UTC, phwb approved these changes

2020-10-16 02:18 UTC, merged