Личный проект: контроль и ограничения (часть 1)
htmlacademy-react/16780-six-cities-5 pull request #8
Opened 2020-10-21 18:50 UTC by aozubrilin

2020-10-22 04:07 UTC, phwb requested changes

2020-10-22 04:07 UTC, phwb commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.updateCityOffers());
а зачем два экшена почему бы не проапдейтить список во время смены города?

2020-10-22 04:07 UTC, phwb commented on src/components/map/map.jsx
> +  BRUSSELS: {coordinates: [50.85, 4.3]},
это нужно унести в моки, оно точно не должно лежать рядом с компонентом

2020-10-22 04:07 UTC, phwb commented on src/index.js
> +        offers={offers}
кажется тебе больше не нужно пробрасывать в App пропсы, вытягивай весь нужный тебе стейт в тех компонентах, которым это требуется

2020-10-22 09:39 UTC, phwb requested changes

2020-10-22 09:39 UTC, phwb commented on src/components/app/app.jsx
> +const App = ({offers, reviews}) => {
тут тоже просы не нужны, а чтобы вытащить офер по айдишнику, то он приходит вторым параметром в функции `mapStatToProps`:
```jsx
const mapStatToProps = (state, ownProps) => {
  const id = ownProps.id
}
```

2020-10-22 09:39 UTC, phwb commented on src/components/favorites-screen/favorites-screen.jsx
> +  const favoritesOffers = offers.filter((offer) => offer.isFavorite);
уноси в mapStateToProps, логики вообще не должно быть в компонентах

2020-10-22 09:39 UTC, phwb commented on src/components/main/main.jsx
> +                <Map offers={currentOffersCity} city={city}/>
подключи компонент к редаксу

2020-10-22 09:39 UTC, phwb commented on src/components/main/main.jsx
>                  <OffersList
подключи компонент к редаксу

2020-10-22 09:39 UTC, phwb commented on src/components/map/map.jsx
> +import {CityCoordinate} from "../../mocks/cities";
я не это имел в виду, координаты должны храниться в структуре либо города, либо оффера

2020-10-22 09:39 UTC, phwb commented on src/components/offer-screen/offer-screen.jsx
> +            <Map offers={[offer, ...nearOffers]} city={offer.city}/>
подключи компонент к редаксу

2020-10-22 11:55 UTC, aozubrilin commented on src/components/main/main.jsx
>                  <OffersList
Почему обязательно  подключать? Ведь и так данные из стора передаются в компонент. И на разных страницах нужны свои данные в этом компоненте?

2020-10-22 11:57 UTC, aozubrilin commented on src/components/map/map.jsx
> +import {CityCoordinate} from "../../mocks/cities";
Следуя из ТЗ "Сервер всегда возвращает информацию только для этих шести городов." Из этого я подумал что будут и приходить координаты центра этих городов? Так же есть координаты оферров.

2020-10-22 11:58 UTC, phwb commented on src/components/main/main.jsx
>                  <OffersList
> И на разных страницах нужны свои данные в этом компоненте

ну все правильно, компонент должен просто выводит список, который пришел к нему в пропсах. а сам список должен формироваться в mapStateToProps.

то есть глупый компонент всегда один, а умных (которые обернут connect) может быть сколько угодно

2020-10-22 11:59 UTC, phwb commented on src/components/main/main.jsx
>                  <OffersList
ну и до кучи ты Main оберну, в самом же Main есть еще обернутые компоненты, которые достают те же самые данные из стейта. при таком подходе зачем тогда Main в connect оборачивать?

2020-10-22 12:02 UTC, phwb commented on src/components/map/map.jsx
> +import {CityCoordinate} from "../../mocks/cities";
все правильно, но логично что структура будет одна, у тебя же не будет двух апи, одна для городов, а другая для координат. скорее всего все будет приходит в одном запросе, так что логично и тут данные хранить в одном объекте

2020-10-22 14:41 UTC, aozubrilin commented on src/components/main/main.jsx
>                  <OffersList
Все равно не понимаю. Например в мэйне  в  OffersList передаем предложения текущего города, а на странице оффера в  OffersList передаем текущий оффер и офферы поблизости.

2020-10-22 14:46 UTC, aozubrilin commented on src/components/app/app.jsx
> +const App = ({offers, reviews}) => {
И вот этот момент пока не понимаю. Надо еще погуглить.

2020-10-22 14:47 UTC, aozubrilin commented on src/components/main/main.jsx
>                  <OffersList
Т.е компонент один, а передаем через пропсы разные данные

2020-10-22 16:12 UTC, phwb commented on src/components/main/main.jsx
>                  <OffersList
> Т.е компонент один, а передаем через пропсы разные данные

все правильно компонент один:
```jsx
 const Offers = () => {}
```

2020-10-22 16:15 UTC, phwb commented on src/components/app/app.jsx
> +const App = ({offers, reviews}) => {
да, посмотри документацию https://react-redux.js.org/using-react-redux/connect-mapstate#ownprops-optional

2020-10-22 21:50 UTC, aozubrilin commented on src/components/main/main.jsx
>                  <OffersList
Я честно пытался понять и погуглить, но нужна "подробная пояснительная бригада".  На данный момент для меня логично, что я из стейnа передаю  данные в props компонента Main, а затем уже в используя тот же props в дочерний компонент OffersList. Что не так в этой цепочке?. В какой компонент, что мне прописать чтоб было правильно?

2020-10-22 21:51 UTC, aozubrilin commented on src/components/app/app.jsx
> +const App = ({offers, reviews}) => {
Получилось вытащить id через ownProps.match.params.id

2020-10-23 04:40 UTC, phwb commented on src/components/favorites-city-list/favorites-city-list.jsx
> +        const offersByСity = offers.filter((offer) => offer.city.name === city);
вот эта логика должны быть в селекторе (mapStateToProps), а не в компоненте

2020-10-23 04:40 UTC, phwb commented on src/components/main/main.jsx
>                  <OffersList
![image](https://user-images.githubusercontent.com/4672733/96957212-78ca0700-1513-11eb-8349-10acba218392.png)

![image](https://user-images.githubusercontent.com/4672733/96957269-a0b96a80-1513-11eb-8315-0677e4f2fab4.png)

![image](https://user-images.githubusercontent.com/4672733/96957335-c5addd80-1513-11eb-9511-8aceb2f6f225.png)

2020-10-23 04:41 UTC, phwb reviewed
уже почти )

2020-10-23 08:14 UTC, aozubrilin commented
Если я все правильно понял. То получается, что абсолютно все данные для компонента должны браться из стейта.

2020-10-23 11:23 UTC, phwb commented
у тебя компоненты (я про умные говорю, которые к стору подключены) должны оставаться как можно более не зависимыми, то есть чтобы ты в любом месте мог их просто подключить и не париться и искать откуда для них взять данные

2020-10-23 11:24 UTC, phwb approved these changes

2020-10-23 11:25 UTC, merged

2020-10-23 11:25 UTC, phwb commented
твой вариант тоже рабочий, но ты каждый раз будешь думать откуда взять данные